### ISSUE TITLE
CBP_Functions.ex5

### ISSUE THREAD

**Issue by geg1700** [TradingToolCrypto/MT5-TradingToolCrypto#29]
SetAnySubWindowText
from the ""CBP_Functions.ex5"

""CBP_Functions.ex5" does not contain the export for "SetAnySubWindowText" /
but this function is being used widely elsewhere within the whole framework

**Comment by geg1700** [comment]
@TradingToolCrypto

**Comment by TradingToolCrypto** [comment]
lib removed "#import "CBP_Functions.ex5"" , replaced with 

`#include <TradingToolCrypto\TT\SymbolStrings.mqh>`
